### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Childii** [MSCMP/MSCMP#30]
Safe call Update failed.

  at (wrapper managed-to-native) UnityEngine.Object:get_name ()
  at MSCMP.Network.PlayerAnimManager.SetDrinkingObject (Byte drinkingObjectId) [0x00000] in <filename unknown>:0 
  at MSCMP.Network.PlayerAnimManager.HandleDrinking (Byte DrinkID) [0x00000] in <filename unknown>:0 
  at MSCMP.Network.PlayerAnimManager.HandleAnimations (MSCMP.Network.Messages.AnimSyncMessage msg) [0x00000] in <filename unknown>:0 
  at MSCMP.Network.NetPlayer.HandleAnimSynchronize (MSCMP.Network.Messages.AnimSyncMessage msg) [0x00000] in <filename unknown>:0 
  at MSCMP.Network.NetWorld.<RegisterNetworkMessagesHandlers>b__8_7 (CSteamID sender, MSCMP.Network.Messages.AnimSyncMessage msg) [0x00000] in <filename unknown>:0 
  at MSCMP.Network.NetMessageHandler+<>c__DisplayClass5_0`1[MSCMP.Network.Messages.AnimSyncMessage].<BindMessageHandler>b__0 (CSteamID sender, System.IO.BinaryReader reader) [0x00000] in <filename unknown>:0 
  at MSCMP.Network.NetMessageHandler.ProcessMessage (Byte messageId, CSteamID senderSteamId, System.IO.BinaryReader reader) [0x00000] in <filename unknown>:0 
  at MSCMP.Network.NetManager.ProcessMessages () [0x00000] in <filename unknown>:0 
  at MSCMP.Network.NetManager.Update () [0x00000] in <filename unknown>:0 
  at MSCMP.MPController.<LateUpdate>b__25_0 () [0x00000] in <filename unknown>:0 
  at MSCMP.Utils.CallSafe (System.String name, MSCMP.SafeCall call) [0x00000] in <filename unknown>:0 
   at System.Environment.get_StackTrace()
   at MSCMP.Client.FatalError(System.String message)
   at MSCMP.Utils.CallSafe(System.String name, MSCMP.SafeCall call)
   at MSCMP.MPController.LateUpdate()

How i can fix this?

**Comment by IvovdBruggen** [comment]
My friend gets this as soon as he starts the van. I think this is reproducible but I don't have the exact steps to at the moment.

**Comment by DarkKostas** [comment]
Was he drinking when he entered the van? Try get some more info please.

**Comment by CurtisVL** [comment]
If this issue still persists in the latest build, please re-open a new issue!
